RESOLUS:

oracle_view_dependencies.py et oracle_table_dependencies.py avec serveur Python sont affiches en texte.
C'est quand 0on utilise le serveur en Python qui liste les scripts au lancement.

============================================================================================================
http://127.0.0.1/PythonStyle/survol/sources/BY_hostname/win32_NetShareEnum.py?xid=hostname:192.168.1.67

uncode les noms des fichiers et folders sinon tres moche (Mais ça marche)
============================================================================================================
Events update:
curr_dir=C:\\Documents and Settings\\Remi\\My Documents\\Reverse\\PythonStyle\\survol/sources_types/file


http://127.0.0.1/PythonStyle/survol/entity.py?xid=com_type_lib:C%3A%5CWINDOWS%5Csystem32%5CLangWrbk.dll
com_type_lib deconne un peu:
<g id="a_node4_5"><a
xlink:href="http://127.0.0.1:80/PythonStyle/survol/entity_list.py?xid=com_type_lib:C:\WINDOWS\system32<TABLE>angWrbk.dll"
xlink:title="script">
=> Pour graphviz, "\L" = "TABLE". Ce quon a fait est de remplacer les \ par des / pour les memmap. 
Le faire pour tout le monde ou bien "escape".

Quand un script a besoin d'un utilitaire qui n'est pas installé,
donner le lien dand un message d'erreur élaboré: Une page qui s'appelle xxx.doc par exemple.
============================================================================================================
pc.property_information:
Il y a peut-etre confusion entre titre et detail.
Le titre doit etre unique et venir en premier, c'est "info".
On peut avoir autant de details qu'on veut.

Dans rdfquery_text.htm les urls sont du style:
http://192.168.1.68/~rchateau/RevPython/survol/entity.py?mode=rdf&_=1422714547625&mode=svg
... et ensuite ca deconne car on s'attend a ce que cgi.args["mode"] renvoie un seul element.

============================================================================================================

Quand on a un timeout (Pour les subserver), apres ca ne repond plus du tout.
[Thu Feb 12 16:27:00 2015] [error] [client 127.0.0.1] (70007)The timeout specified has expired: ap_content_length_filter: apr_bucket_read() failed, referer: http://127.0.0.1/PythonStyle/survol/entity.py

Verifier si on peut relancer le feeder ?
Ce serait bien si on pouvait rediriger automatiquement ?
Ou bien forcer au rechargement ?
SVG n'a pas de meta refresh.

Toutefois: Au lieu de rediriger, on pourrait envoyer un page HTML qui contient un DIV avec comme URL,
le lien vers du SVG (Avec le port special) et le meta-refresh qui va recharger toutes les X minutes,
comme ca on est jamais en timeout.

Et on met un peu de sauce sur la page HTML pour voir ou on en est.
Attention car ce ne sera plus une page SVG, donc on ne peut pas la refiler autre part.
Et donc la redirection ne doit etre utilisee que pour les navigateurs.
Est-ce que le lien d'origine fonctionne et est capable de redemarrer le feeder ?

============================================================================================================
Quand nmap renvoie le port http, on doit pouvoir cliquer dessus et ne pas arriver sur 
entity.py avec adresse: Ou bien, dans le entity.py, si le port est 80, on doit avoir le lien html_data.

============================================================================================================
le nmap qui interroge les ports ne devrait pas etre limite a 127.0.0.1 mais au contraire le sous-reseau. 
============================================================================================================
Ajouter la commande:

nmap -oX - -T5 192.168.1.0/24

Tres rapide et complete apparemment:
http://www.cyberciti.biz/networking/nmap-command-examples-tutorials/
============================================================================================================
Automatic refresh when displaying the processes tree:
- Some links are there without nodes.
- Impossible to delete the nodes of this url (When clicking Del in the summary window)
============================================================================================================

Ca deconne probablement a cause du tilda: Tester avec des noms de fichiers tres longs ?
http://127.0.0.1/PythonStyle/survol/entity.py?xid=file:C%3A%5CDOCUME~1%5CRemi%5CLOCALS~1%5CTemp%5CSkype%5CDbTemp%5Ctemp-968iZH8Qs4gRIszFZIEJETGX

file_directory sur un ficheir qui n'est pas un directory:
http://127.0.0.1/PythonStyle/survol/sources_types/file/file_directory.py?xid=file:C%3A%5CDocuments%20and%20Settings%5CRemi%5CApplication%20Data%5CSkype%5Cshared_dynco%5Cdc.db
Ca n'affiche rien: Soit on ne propose pas la focntion, soit on  met un message d'information.

http://127.0.0.1:4444/infoqueues
Sous XP ca affiche en texte, ca doit ajouter une cochonnerie au debut.
# TODO: Est-ce vraiment necessaire ?????????????
# Peut-etre oui, a cause des sockets ?
def WrtAsUtf(out,str):
	out.write( str.encode('utf-8') )
Peut-etre ca, mais pas certain car autre erreur. Voir deja si ca casse Win8.
		# Python 3.2.3 (Donc Win8)
		# self.wfile.write( str.encode() )
		self.wfile.write( str.encode('utf-8') )

* http://127.0.0.1:8000/survol/sources_types/CIM_Directory/file_directory.py?xid=CIM_Directory.Name=C%3A%2F%2FUsers%2Frchateau%2FDeveloppement%2FReverseEngineeringApps%2FPythonStyle%2Fhtbin
Faulty link, probably because it contains "htbin"

* http://127.0.0.1:8000/survol/entity.py?xid=python/package.Id=azure-storage
Importing azure-storage: Error (, ImportError('No module named azure-storage',), )

* http://127.0.0.1:8000/survol/class_type_all.py?xid=http%3A%2F%2F192.168.1.88%3A5988%2Froot%2Fcimv2%3ACIM_Indication.
Cannot connect to WMI server with params:{'password': 'XXXYYYZZZ', 'computer': '192.168.1.88', 'namespace': 'root/cimv2'}.Exc=(, x_wmi(), )
Should not use WMI on a Linux password. Maybe check the port number.

* http://127.0.0.1:8000/survol/entity.py?xid=CIM_DataFile.
When displaying data file, should be able to see it in MIME just like when viewing directories.

# Cleanup TmpDirToDel (Quand on affiche du doxygen)

* http://127.0.0.1:8000/survol/entity.py?xid=CIM_Directory.Name=C%3A\
Ca plante graphviz, on ne le detecte pas et eventuellement on affiche un ancien svg
qui n aurait pas ete zappe.
Le probleme est le backslash a la fin de la ligne.

* Le texte des Usable ne doit pas contenir de "<>":
def Usable(entity_type,entity_ids_arr):
	"""Psutil version >= 4.0.0"""

* Dans file_directory, les sous-noeuds correspondant aux scripts ne pointent pas vers leur parent.

* CIM_LogicalDisk pas defini et n a pas d ontologie tant sous Unix que Windows.

* http://primhillcomputers.ddns.net/Survol/survol/entity.py?xid=python/package.Id=openlmi-scripts-networking
Dans les modules Python, impossible d afficher ceux avec des tirets. Qu est ce que ces tirets signifient ?
Importing openlmi-scripts-networking: Error (, ImportError('No module named openlmi-scripts-networking',), )
Et d ailleurs l affichage des modules n est pas hierarchique mais a plat.

* Probleme affichage "Usability MS-Dos Batch processes" et "Usability Python processes"
dans http://127.0.0.1:8000/survol/entity.py?xid=CIM_Process.Handle=3604.
C est quand tout un directory de scripts n est pas affiche a cause de Usable() dans le __init__.py :
 Ca a l'air de fonctionmer.

* Dans la page javascript, pas moyen de mettre la redirection de "top":
Error loading:http://127.0.0.1:23456/?xid=:&mode=rdf:error

* Affiche pas bien le nom du groupe.: http://127.0.0.1/PythonStyle/survol/entity.py?xid=group:HelpServicesGroup&mode=svg

* There can only be one summary window because they all have the same name.
At least when it is the same machine.
This must be changed otherwise cannot drag'n'drop between several windows.


win_directory_changes se plante

DataSkypeshared_dyncodc.db pid=4884
(srv)ReqHnd:2015-03-11 06:27:21 p=4180 Getting queue entityId=C:Documents and SettingsRemiApplication DataSkypeshared_dyncodc.db
(srv)ReqHnd:2015-03-11 06:27:21 p=4180 Getting pid
(srv)ReqHnd:2015-03-11 06:27:21 p=4180 pidFeeder 4884 not there.


Quand entity=file:xxx, toujours ajouter le directory au-dessus sinon c'est pas commode.




http://127.0.0.1/PythonStyle/survol/entity.py?xid=com_type_lib_entry,coclass:C:\WINDOWS\System32\comsnap.dll_(6)
Ca n'affiche rien.
